// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Fixed fixed1;
    
    private Gtk.EventBox eventbox1;
    
    private Gtk.Image image2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.fixed1 = new Gtk.Fixed();
        this.fixed1.WidthRequest = 71;
        this.fixed1.HeightRequest = 96;
        this.fixed1.Events = ((Gdk.EventMask)(256));
        this.fixed1.Name = "fixed1";
        this.fixed1.HasWindow = false;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.eventbox1 = new Gtk.EventBox();
        this.eventbox1.WidthRequest = 71;
        this.eventbox1.HeightRequest = 96;
        this.eventbox1.Events = ((Gdk.EventMask)(256));
        this.eventbox1.Name = "eventbox1";
        this.eventbox1.AboveChild = true;
        // Container child eventbox1.Gtk.Container+ContainerChild
        this.image2 = new Gtk.Image();
        this.image2.WidthRequest = 71;
        this.image2.HeightRequest = 96;
        this.image2.Events = ((Gdk.EventMask)(768));
        this.image2.ExtensionEvents = ((Gdk.ExtensionMode)(1));
        this.image2.Name = "image2";
        this.image2.Xalign = 1F;
        this.eventbox1.Add(this.image2);
        this.fixed1.Add(this.eventbox1);
        Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.eventbox1]));
        w2.X = 118;
        w2.Y = 143;
        this.Add(this.fixed1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 559;
        this.DefaultHeight = 354;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.eventbox1.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.OnEventbox1ButtonReleaseEvent);
    }
}
