// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private CardLib.CardRow cardrow1;
    
    private CardLib.CardRow cardrow2;
    
    private CardLib.CardRow cardrow3;
    
    private CardLib.CardRow cardrow4;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.cardrow1 = new CardLib.CardRow();
        this.cardrow1.WidthRequest = 491;
        this.cardrow1.HeightRequest = 98;
        this.cardrow1.Events = ((Gdk.EventMask)(256));
        this.cardrow1.Name = "cardrow1";
        this.vbox1.Add(this.cardrow1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.cardrow1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.cardrow2 = new CardLib.CardRow();
        this.cardrow2.WidthRequest = 491;
        this.cardrow2.HeightRequest = 98;
        this.cardrow2.Events = ((Gdk.EventMask)(256));
        this.cardrow2.Name = "cardrow2";
        this.vbox1.Add(this.cardrow2);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.cardrow2]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.cardrow3 = new CardLib.CardRow();
        this.cardrow3.WidthRequest = 491;
        this.cardrow3.HeightRequest = 98;
        this.cardrow3.Events = ((Gdk.EventMask)(256));
        this.cardrow3.Name = "cardrow3";
        this.vbox1.Add(this.cardrow3);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.cardrow3]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.cardrow4 = new CardLib.CardRow();
        this.cardrow4.WidthRequest = 491;
        this.cardrow4.HeightRequest = 98;
        this.cardrow4.Events = ((Gdk.EventMask)(256));
        this.cardrow4.Name = "cardrow4";
        this.vbox1.Add(this.cardrow4);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.cardrow4]));
        w4.Position = 3;
        w4.Expand = false;
        w4.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 559;
        this.DefaultHeight = 458;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
